version: '3'
services:
  kkuziri:
    build: ./
    image: scvgoe/kkuziri:latest
    ports:
      - 80:80
      - 443:443
    links:
      - postgresql
    volumes:
      - ./letsencrypt/etc:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /backup
  postgresql:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    tmpfs:
      - /backup
    environment:
      POSTGRES_PASSWORD: kkuziri
      POSTGRES_USER: kkuziri
    ports:
      - 5432:5432
